### ISSUE TITLE
Wrong database configuration

### ISSUE THREAD

**Issue by rodrigo-sene** [onesaitplatform/onesaitplatform-revolution-magrathea#2]
The documentation to run the application is very unclear.
In this link: https://onesaitplatform.atlassian.net/wiki/spaces/OP/pages/7897242/Develop+How+to+execute+the+platform+in+my+Windows+PC+with+OP-SDK
 The documentation says that you must create a new database with name onesaitplatform_config and root password changeIt!, but after doing that you cant run modules that need this database like iot-broker and config-init.
 Caused by: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.

 In application.yml the database password is encrypted, even in a development profile.
 The project must simplify the documentation to run applications alone.

 In my case I just create a Docker compose to run iot-broker:
```

version: '3'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: changeIt!
      MYSQL_DATABASE: onesaitplatform_config
    ports:
      - "3306:3306"
  rabbitMq-developent:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
```
Even if you run this docke file and try to start iot-broker with a simple 
```
mvn spring-boot:run
```
An Error will be thrown.
